#!/bin/bash

(test "$1" != "create" && test "$1" != "append") && echo "Usage: init_sync [create|append]" && exit

root=$(git rev-parse --show-toplevel)
sync_file=$root/html/wp-content/themes/taco-theme/sync

if [ "$1" == "create" ]; then
  echo "#!/bin/bash" > $sync_file
  chmod +x $sync_file
fi

#Add to pre push hook
cat > $root/.git/hooks/pre-push <<EOF
root=\$(git rev-parse --show-toplevel)
current_branch=\$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
\$root/html/wp-content/themes/taco-theme/sync \$1 \$current_branch
EOF
chmod +x $root/.git/hooks/pre-push

another="y"

while [ "$another" == "y" -o "$another" == "Y" ]
do
  echo "Enter the remote you want to sync [origin]"
  read remote
  test "$remote" == "" && remote="origin"

  echo "Enter the branch you want to sync [master]"
  read branch
  test "$branch" == "" && branch="master"

  while [ "$url" == "" ]
  do
    echo "Enter the ssh path to the server this branch gets deployed to (e.g. user@server.com)"
    read url

    test "$url" == "" && echo "You must specify your ssh path"
  done

  while [ "$path" == "" ]
  do
    echo "Enter the absolute path to the deployment (e.g. /var/www/vhosts/project)"
    read path

    test "$path" == "" && echo "You must specify your ssh path"
  done

  #rsync
  echo "${remote}_${branch}=\"rsync --delete -avz ./html/wp-content/themes/taco-theme/_/dist $url:$path/html/wp-content/themes/taco-theme/_\"" >> $sync_file
  echo "test \"\$1\" == \"${remote}\" && test \"\$2\" == \"${branch}\" && \$${remote}_${branch};" >> $sync_file

  echo "Add another branch? [y/N]"
  read another

  test "$another" == "" && another="n"
done
