#!/bin/bash

(test "$1" != "create" && test "$1" != "append") && echo "Usage: init_sync [create|append]" && exit

if [ "$1" == "create" ]; then
  echo "#!/bin/bash" > sync
  chmod +x sync
fi

#Add to pre push hook
cat > ../../../../.git/hooks/pre-push <<EOF
  current_branch=\$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
  ./html/wp-content/themes/taco-theme/sync \$current_branch
EOF
chmod +x ../../../../.git/hooks/pre-push

another="y"

while [ "$another" == "y" -o "$another" == "Y" ]
do
  echo "Enter the branch you want to sync (e.g. master)"
  read branch
  echo "Enter the ssh path to the server this branch gets deployed to (e.g. user@server.com)"
  read url
  echo "Enter the absolute path to the deployment (e.g. /var/www/vhosts/project)"
  read path

  #rsync
  echo "$branch=\"rsync --delete -az ./html/wp-content/themes/taco-theme/_/dist $url:$path/html/wp-content/themes/taco-theme/_\"" >> sync
  echo "test \$1 == \"$branch\" && \$$branch;" >> sync

  echo "Add another branch? [y/N]"
  read another

  test "$another" == "" && another="n"
done
