<?php

namespace Faker\Provider;

class Resource extends \Faker\Provider\Base
{

  /**
   * get a random resource title
   * @return string
   */
  public function resourceTitle()
  {
    return $this->randomElement($this->getResourceTitles());
  }


  /**
   * get an array of resource titles
   * @return array
   */
  public function getResourceTitles()
  {
      return array(
        'Accreditation',
        'Capacity building, Education and Training in health promotion',
        'Community Health Evaluation',
        'Global Road Safety',
        'Health Promotion Effectiveness',
        'International Health Promotion on Programmes and Strategies',
        'Non-Communicable Diseases',
        'Physical Activity',
        'School Health',
        'Social Determinants of Health and Health Inequalities',
        'Tobacco Control',
        'IUHPE Research Report Series Research',
        'UN important resources for health promotion',
        'Impact of point-of-sale tobacco display bans: findings from the International Tobacco Control Four Country Survey',
        'Changes in Ambulance Calls Following Implementation of a Smokefree Law and its Extension to Casinos',
        'The Status of Implementation of the FCTC Illicit Trade Protocol and Global and Regional Solutions for Controlling Illicit Tobacco Trade',
        'Do State Expenditures on Tobacco Control Programs Decrease Use of Tobacco Products Among College Students? (Working Paper)',
        'The Economics of Tobacco Taxation',
        'The Impact of Retail Cigarette Marketing Practices on Youth Smoking Uptake',
        'Relation Between Newspaper Coverage of Tobacco Issues and Smoking Attitudes and Behaviour Among American Teens',
        'Public Health Obesity-Related TV Advertising: Lessons Learned from Tobacco',
        'The Economic Impact of Clean Indoor Air Laws',
        'IARC Handbooks of Cancer Prevention, Tobacco Control,Vol 12: Methods for Evaluating Tobacco Control Policies',
        'The Economics of Tobacco Taxation In Massachusetts',
        'News on Tobacco and Public Attitudes Toward Smokefree Air Policies in the United States.',
        'Why is Tobacco Price Manipulation a Problem? Point-of-Sale Marketing and Cigarette Smoking',
        'Enhancing Compliance with Tobacco Control Policies',
        'Effectiveness of Smoke-Free Policies',
        'Tobacco Taxation',
        'The Economics of Tobacco and Tobacco Control',
        'Smoking, Food Insecurity, and Tobacco Control',
        'IARC Handbooks of Cancer Prevention, Tobacco Control, Vol. 13: Evaluating the Effectiveness of Smoke-Free Policies',
        'Cigarette Smoking Prevalence and Policies in the 50 States: An Era of Change',
        'The Economics of Smoke-Free Air Policies',
        'The Economics of Tobacco Control: Smoke-Free Air Policies and Tobacco Taxes',
        'Depression, Suicide, Tobacco Control Policies, and Cigarette Smoking Among High School Students',
        'Handbook of Research on Cost&ndash;Benefit Analysis, Ch 19: The Value of the 1964 Surgeon General&rsquo;s Report',
        '[Commentary] Financial Stress and Smoking Cessation - A Silver Lining to the Dark Clouds of the Global Economy?',
        'Looking Backward and Looking Forward: Lessons Learned from Alcohol and Tobacco Taxes and Implications for Obesity Prevention',
        'RWJF and Tobacco Policy Research: One Researcher&rsquo;s Perspective',
        'Tobacco Control Lessons Learned: The Impact of State and Local Policies',
        'Gender, Women, and the Tobacco Epidemic:Taxation and the Economics of Tobacco Control',
        'Tobacco Research: Highest Priorities',
        'The Economics of Tobacco and Tobacco Taxation in India',
        'Applying Tobacco Control Lessons to Obesity: Taxes and Other Pricing Strategies to Reduce Consumption',
        'A Significant Cigarette Tax Rate Increase in North Carolina Would Produce a Large, Sustained Increase in State Tobacco Tax Revenues',
        'Pricing Strategies for Tobacco, Healthy Eating, and Physical Activity',
        'Taxes as a Tool for Promoting Public Health: Lessons from Tobacco Taxation',
        'Tracking Tobacco Legislation: SmokeLess States Legislative Coding and Evaluation, Overview, Methods, and Process',
        'Cigarette Excise Taxation: The Impact of Tax Structure on Prices, Revenues, and Cigarette Smoking',
        'A Significant Cigarette Tax Rate Increase In Ohio Would Produce A Large, Sustained Increase In State Tobacco Tax Revenues',
        'Surveillance of Tobacco Industry Retail Marketing Activities of Reduced Harm Products',
        'State-level Tobacco Control Policies and Youth Smoking Cessation Measures',
        'Tobacco Excise Tax Structure: Implications for Public Health',
        'Economics of Tobacco Control -November 2010',
        'Effectiveness of Tax and Price Policies in Tobacco Control',
        'Menthol and Non-Menthol Smoking: The Impact of Prices and Smoke-Free Air Laws',
        'The Economic Impact of the 2008 Kansas City Missouri Smoke-Free Air Ordinance',
        'Self-Reported Price of Cigarettes, Consumption and Compensatory Behaviours in a Cohort of Mexican Smokers Before and After a Cigarette Tax Increase',
        'A Significant Cigarette Tax Rate Increase In Illinois Would Produce A Large, Sustained Increase In State Tobacco Tax Revenues',
        'Socio-Economic Variation in Price Minimizing Behaviors: Findings from the International Tobacco Control (ITC) Four Country Survey',
        'Commentary on Ross et al. (2011): Beyond Cigarette Taxes &ndash; The Need for Research on Other Cigarette Pricing Policies',
        'The Economic Impact of State Cigarette Taxes and Smoke-free Air Policies on Convenience Stores',
        'Do State Expenditures on Tobacco Control Programs Decrease Use of Tobacco Products Among College Students?',
        'Leading Health Indicators for Healthy People 2020 &ndash; Letter Report',
        'Lessons Learned from Tobacco and Alcohol Taxation and Implications for Obesity Prevention',
        'IMPACT: Smokers and Smoking-Related Deaths',
        'The Economic Impact of the 2008 Pennsylvania Clean Indoor Air Act',
        'The Impact of Tax and Smoke-Free Air Policy Changes',
        'What Gets Measured, Gets Changed: Evaluating Law and Policy for Maximum Impact -April 2011',
        'The State of Tobacco Control in Nebraska: One Economist&rsquo;s Perspective',
        'Best Practices in Tobacco Taxation',
        'How do Price Minimizing Behaviors Impact Smoking Cessation: Findings from the International Tobacco Control (ITC) Four Country Survey',
        'IARC Handbooks of Cancer Prevention,Tobacco Control, Vol.14: Effectiveness of Tax and Price Policies for Tobacco Control',
        'Quit Attempts and Quit Rates Among Menthol and Nonmenthol Smokers in the United States',
        'The Demand for Cigarettes in Ireland',
        'Economic Impact of Smoke-Free Air Policies',
        'Public Policy Versus Individual Rights and Responsibility: An Economist&#039;s Perspective',
        'The Oxford Handbook of the Social Science of Obesity: Lessons for Obesity Policy from the Tobacco Wars',
        'A Rational Taxation System of Bidis and Cigarettes to Reduce Smoking Deaths in India',
        'The Economic Impact of State Cigarette Taxes and Smoke-Free Air Policies on Convenience Stores - November 2011',
        'Socioeconomic Differences in the Impact of Smoking Tobacco and Alcohol Prices on Smoking in India',
        'Youth Access Tobacco Possession, Use, and Purchase Laws: Measures of State and Local Enforcement',
        'Nicotine and Tobacco Research Special Supplement: Economic Aspects of Tobacco Use in Low- and Middle-Income Countries',
        'ITC Cross-Country Comparison Report: Tobacco Price and Taxation',
        'Tobacco Taxes as a Tobacco Control Strategy',
        'Mechanisms of Legal Effect: Perspectives from Economics',
        'Tax and Price Policies for Tobacco Control',
        'Tobacco Tax Structure and Tobacco Use',
        'Impact of Tobacco Pricing and Taxation: Economic Analysis Using ITC Project Data',
        'Preventing Tobacco Use Among Youth and Young Adults: A Report of the Surgeon General',
        'Tax, Price and Tobacco Use',
        'The Effects of Smoking-Related Television Advertising on Smoking and Intentions to Quit Among Adults in the United States: 1999-2007',
        'Taxation as Public Health Policy - April 2012',
        'Monitoring and Assessing the Impact of Tax and Price Policies on United States&rsquo; Tobacco Use -May 2012',
        'Frank Chaloupka Q&amp;A: Study Shows 2009 Federal Tobacco Tax Helped Cut Youth Smoking',
        'Taxation as Public Health Policy -May 2012',
        'The Impact of the 2009 Federal Tobacco Excise Tax Increase on Youth Tobacco Use',
        'The Economics of Tobacco and Tobacco Taxation in Bangladesh',
        'Taxation as Public Health Policy -June 2012',
        'Tobacco Product Regulation: FDA&rsquo;s Economic Impact Analysis',
        'Tobacco Taxes and Tobacco Use: Global Evidence',
        'Tobacco Taxes and Tobacco Use: Global Evidence (Spanish Version)',
        'The Science Behind Tobacco Taxation',
        'Globalization of the Tobacco Industry &ndash; One Economist&rsquo;s Perspective -August 2012',
        'A Cross-Country Study of Cigarette Prices and Affordability: Evidence From the Global Adult Tobacco Survey',
        'The Economics of Tobacco and Tobacco Taxation in the Philippines',
        'What Can We Learn From Tobacco?',
        'Taxation as Obesity Control Policy',
        'Comparing Self-Report and Archival Cigarette Prices: Evidence from the United States and Canada',
        'The Impact of Cigarette Excise Taxes on Smoking Cessation Rates From 1994 to 2010 in Poland, Russia, and Ukraine',
        'Tobacco Taxes: A Win-Win Measure for Fiscal Space and Health',
        'Differential Effects of Price Changes on Adult Smoking Behaviors',
        'High-Resolution Behavioral Economic Analysis of Cigarette Demand to Inform Tax Policy',
        'Cigarette Pricing Differs by U.S. Neighborhoods',
        'Comparing Effects of Tobacco Use Prevention Modalities: Need for Complex Systems Models',
        'Globalization of the Tobacco Industry and Implications for Tobacco Control &ndash; One Economist&rsquo;s Perspective',
        'Monitoring and Assessing the Impact of Tax and Price Policies on US Tobacco Use',
        'Tobacco Product Licensing, Production &amp; Distribution',
        'Restrictions on Tobacco Use, Sales &amp; Marketing',
        'Tobacco, Economics and Development in the 21st Century',
        'The Recent and Projected Public Health and Economic Benefits of Cigarette Taxation in Greece',
        'Relevant Trends in Global Tobacco',
        'Economics of Tobacco Control -August 2013',
        'Economic Research on Tobacco-Tax Avoidance &amp; Evasion',
        'Tax and Price Policies',
        'New Findings from Research on the Economics of Tobacco Use',
        'Introduction to Tobacco Control Economics: Best Practices in Taxation',
        'Introduction to Tobacco Control Economics: Costs of Smoking and Cost Effectiveness of Tobacco Control Interventions',
        'Emerging Evidence Needs in the Economic Aspects of Tobacco Control',
        'Left-digit price effects on smoking cessation motivation',
        'Cigarette Excise Tax Structure and Cigarette Prices: Evidence From the Global Adult Tobacco Survey and the U.S. National Adult Tobacco Survey',
        'The Effects of Prices on Cigarette Use Among Youths in the Global Youth Tobacco Surveys',
        'Exploring the Relationship Between Cigarette Prices and Smoking Among Adults: A Cross-Country Study of Low- and Middle-Income Nations',
        'The Influence of Prices on Youth Tobacco Use in India',
        'The Economics of Tobacco Use in Jordan',
        'Who Quits? An Overview of Quitters in Low- and Middle-Income Countries',
        'Market Structures, Socioeconomics, and Tobacco Usage Patterns in Madagascar',
        'Conference Report on Tobacco Taxes in Central America: Current Situation and Opportunities to Reduce Prevalence and Increase Fiscal Revenues',
        'The Effect of Prices on Cigarette Use Among Youths in the Global Youth Tobacco Survey',
        'Tax, Price and Cigarette Brand Preferences: A Longitudinal Study of Adult Smokers from the ITC Mexico Survey',
        'Cigarette Brand Loyalty in Australia: Findings from the ITC Four Country Survey',
        'The distribution of cigarette prices under different tax structures: findings from the International Tobacco Control Policy Evaluation (ITC) Project',
        'Trends in the use of premium and discount cigarette brands: findings from the ITC US Surveys (2002&ndash;2011)',
        'A novel approach to estimating the prevalence of untaxed cigarettes in the USA: findings from the 2009 and 2010 international tobacco control surveys',
        'Chinese smokers&rsquo; cigarette purchase behaviours, cigarette prices and consumption: findings from the ITC China Survey',
        'The economics of tobacco control: evidence from the International Tobacco Control (ITC) Policy Evaluation Project',
        'Death and taxes: using the latter to reduce the former',
        'Who Purchases Cigarettes from Cheaper Sources in China? Findings from the ITC China Survey',
        'The Choice of Discount Brand Cigarettes: A Comparative Analysis of International Tobacco Control Surveys in Canada and the USA (2002&ndash;2005)',
        'Cigarette Graphic Warning Labels and Smoking Prevalence in Canada: a Critical Examination and Reformulation of the FDA Regulatory Impact Analysis',
        'Cigarette Tax Avoidance and Evasion: Findings from the International Tobacco Control Policy Evaluation (ITC) Project',
        'Socioeconomic and Country Variations in Cross-Border Cigarette Purchasing as Tobacco Tax Avoidance Strategy. Findings from the ITC Europe Surveys ',
        'The Price Sensitivity of Cigarette Consumption in Bangladesh: Evidence from the International Tobacco Control (ITC) Bangladesh Wave 1 (2009) and Wave 2 (2010) Surveys ',
        'Trends in the Use of Premium and Discount Cigarette Brands: Findings from the ITC US Surveys ',
        'The Effect of Cigarette Prices on Brand-Switching in China: a Longitudinal Analysis of Data from the ITC China Survey',
        'Fact Sheet: Tobacco Taxes in Pakistan',
        'ITC Cross-Country Comparison Report Tobacco Price and Taxation',
        'The Economics of Tobacco and Tobacco Taxation in Pakistan',
        'The Impact of Price and Tobacco Control Policies on the Demand for Electronic Nicotine Delivery Systems',
        'The Availability of Electronic Cigarettes in US Retail Outlets, 2012: Results of Two National Studies',
        'A Baseline Understanding of State Laws Governing E-Cigarettes',
        'Economic Impact of a Noncomprehensive Smoke-Free Air Law',
        'Probing the Smoking&ndash;Suicide Association: Do Smoking Policy Interventions Affect Suicide Risk?',
        'Standardized Tobacco Assessment for Retail Settings (STARS) Survey',
        'Electronic Cigarettes: A Policy Statement From the American Heart Association',
        'How Much Cigarette Tax Avoidance Is There in the US? Different Estimates from Smoker Surveys and Physical Pack Collection Methods',
        'Relative Tax Rates, Proximity and Cigarette Tax Avoidance: Evidence from a National Sample of Littered Cigarette Packs',
        'A Comprehensive Examination of Price Elasticities of Tobacco Products: Evidence from Commercial Store Scanner Data',
        'State Approaches to Addressing Cigarette Tax Avoidance and Other Tobacco Product Taxation, 2005&ndash;2014',
        'Is the Cigarette Price Effect Nonlinear?',
        'The Impact of Electronic Cigarette Sales on Cigarette Sales, 2007&ndash;2013',
        'Understanding State Minimum Pricing/Markup Tobacco Product Regulatory Schemes, 2005&ndash;2014',
        'State Tax Laws Governing Tribal Tobacco Sales',
        'Adult Tobacco Survey: Dual/poly-use of e-cigarettes with other tobacco products and other focused analyses',
        'Trends in the Retail Tobacco Marketplace, 1999&ndash;2012',
        'Overview of FCTC Article 6 Guidelines at COP6',
        'The Economics of Tobacco Control &ndash; Lessons Learned from International Experiences',
        'The Impact of Potential FDA Regulatory Actions on Smoking Prevalence among Youth and Adults: Findings from Global Adult Tobacco Survey and Global Youth Tobacco Survey',
        'An Evaluation of FDA&rsquo;s Analysis of the Costs and Benefits of the Graphic Warning Label Regulation',
        'The Effect of Smoke-Free Air Law in Bars on Smoking Initiation and Relapse among Teenagers and Young Adults',
        'A Significant Cigarette Tax Rate Increase in Ohio Would Produce a Large, Sustained Increase in State Tobacco Tax Revenues',
        'Cigarette Price and Other Factors Associated with Brand Choice and Brand Loyalty in Zambia: Findings from the ITC Zambia Survey',
        'Weight Control Belief and Its Impact on the Effectiveness of Tobacco Control Policies on Quit Attempts: Findings from the ITC 4 Country Project',
        'The Impact of Prices and Taxes on the Use of Tobacco Products in Latin America and the Caribbean',
        'Get the Facts: Minnesota&#039;s 2013 Tobacco Tax Increase Is Improving Health',
        'Briefing slides for Understanding the U.S. Illicit Tobacco Market: Characteristics, Policy Context, and Lessons from International Experience',
        'Understanding the U.S. Illicit Tobacco Market:  Characteristics, Policy Context, and Lessons from International Experiences',
        'Effect of Cigarette Tax Increase in Combination with Mass Media Campaign on Smoking Behaviour in Mauritius: Findings from the ITC Survey',
        '50 State Law Approaches to Reducing Cigarette Tax Avoidance and Taxing OTPs, 2005&ndash;2014',
        'Understanding the Relationship Between State Minimum Pricing Laws and Discount Mechanisms, 2005&ndash;2014',
        'The Use of Legal, Illegal, and Roll-Your-Own Cigarettes to Increasing Tobacco Excise Taxes and Comprehensive Tobacco Control Policies: Findings from the ITC Uruguay Survey',
        'A Significant Cigarette Tax Rate Increase in Kansas Would Produce a Large, Sustained Increase in State Tobacco Tax Revenues',
        'Understanding and Measuring Cigarette Tax Avoidance and Evasion: A Methodological Guide ',
        'Undermining Government Tax Policies: Common Strategies Employed by the Tobacco Industry in Response to Tobacco Tax Increases',
        'The Association between Tax Structure and Cigarette Price Variability: Findings from the International Tobacco Control Policy Evaluation (ITC) Project',
        'The Use of Legal, Illegal, and Roll-Your-Own Cigarettes to Increasing  Tobacco Excise Taxes and Comprehensive Tobacco Control Policies: Findings from the ITC Uruguay Survey',
        'The Association between Tax Structure and Cigarette Price Variability: Findings from the International Tobacco Control Policy Evaluation (ITC) Project',
        'Differential Responsiveness to Cigarette Price by Education and Income among Adult Urban Chinese Smokers',
        'Controlling Illicit Tobacco Trade: International Experience',
        'Measures to Control Illicit Tobacco Trade',
        'Approaches for Controlling Illicit Tobacco Trade &mdash; Nine Countries and the European Union',
        'Use of Tobacco Tax Stamps to Prevent and Reduce Illicit Tobacco Trade &mdash; United States, 2014',
        'Podcast: The Economics of Tobacco Control (Part 2)',
        'Methodology Report for State Tobacco Control and Prevention Expenditures: FY 2008&ndash;2011',
        'State Tobacco Control Program Spending &mdash; United States, 2011',
        'Sociodemographic Disparities in Local Smoke-Free Law Coverage in 10 States',
        'Differential Taxes for Differential Risks&mdash;Toward Reduced Harm from Nicotine-Yielding Products',
        'State Cigarillo Taxation Laws, Selected Years 2005&ndash;2014',
        'State Cigar Taxation Laws, Selected Years 2005&ndash;2014',
        'State Dissolvable Tobacco Product Taxation Laws, Selected Years 2005&ndash;2014',
        'State Dry Snuff Taxation Laws, Selected Years 2005&ndash;2014',
        'State Little Cigar Taxation Laws, Selected Years 2005&ndash;2014',
        'State Moist Snuff Taxation Laws, Selected Years 2005&ndash;2014',
        'States with Non-Cigarette Tobacco Product Taxation as of January 1, 2014',
        'State Pipe Tobacco Taxation Laws, Selected Years 2005&ndash;2014',
        'State Roll-Your-Own Tobacco Taxation Laws, Selected Years 2005&ndash;2014',
        'State Smokeless Tobacco Product Taxation Laws, Selected Years 2005&ndash;2014',
        'State Snus Taxation Laws, Selected Years 2005&ndash;2014',
        'Alabama Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Alaska Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Arizona Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Arkansas Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'California Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Colorado Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Connecticut Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'District of Columbia Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Delaware Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Florida Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Georgia Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'Tobacco Product Taxation: An Analysis of State Tax Schemes Nationwide, Selected Years, 2005&ndash;2014',
        'Hawaii Tobacco Product Taxation State Fact Sheet, Selected Years 2005&ndash;2014',
        'An Oklahoma History of Cigarette Taxation',
        'Idaho Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Illinois Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Indiana Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Iowa Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Kansas Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Kentucky Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Louisiana Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Maine Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Maryland Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Massachusetts Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Michigan Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Minnesota Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Mississippi Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Missouri Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Montana Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Nebraska Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Nevada Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'New Hampshire Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'New Jersey Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'New Mexico Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'New York Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'North Carolina Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'North Dakota Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Ohio Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Oklahoma Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Oregon Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Pennsylvania Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Rhode Island Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'South Carolina Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'South Dakota Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Tennessee Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Texas Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Utah Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Vermont Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Virginia Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Washington Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'West Virginia Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Wisconsin Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Wyoming Tobacco Product Taxation State Fact Sheet, Selected Years 2005-2014',
        'Companion Slides for Tobacco Product Taxation: An Analysis  of State Tax Schemes Nationwide, Selected Years, 2005-2014',
        'State Non-Cigarette Tobacco Product Taxation Data File and Codebook',
        'Do Taxes Make You Healthier?',
        'Absolutely No Question Raising Tax on Tobacco Reduces Smoking',
        'Editorial: Congress Must Not Weaken Nation&rsquo;s Fight Against Tobacco',
        'Tobacco Control Is Smart Economics (Amongst Other Things)',
        'Cigarette Taxation in Kenya at the Crossroads: Evidence and Policy Implications',
        'Global Hazards of Tobacco and the Benefits of Smoking Cessation and Tobacco Taxes',
        'Cigarette Pricing Lowest in Black Neighborhoods: 2010&ndash;2012',
        'Preventing and Reducing Illicit Tobacco Trade in the United States',
        'The Association between Point-of-Sale Advertising Bans and Youth Experimental Smoking: Findings from the Global Youth Tobacco Survey (GYTS)',
        'Newsletter Issue 1: October 2009',
        'May 2015 Issue 18',
        'Blowing Open the Bottleneck',
        'NJNI Program Launch 2009',
        'Annual Meeting: 2009 - First Cohort of New Jersey Nursing Scholars Meet, Mingle and Learn',
        'Learning Needs of the Nursing Student',
        'Multicultural Education',
        'Carnegie Foundation: Educating Nurses: A Call for Radical Transformation - Book Highlights',
        'Clinical Education: Effective Practices and Partnerships',
        'NJNI Program Update 2010',
        'NACNEP: Addressing New Challenges Facing Nursing Education: Solutions for a Transforming Healthcare Environment',
        'Fostering Civility In Nursing',
        'Annual Meeting: 2010 - Insight and Inspiration at New Jersey Nursing Initiative',
        'IOM Report: The Future of Nursing: Leading Change, Advancing Health',
        'Introduction to the Role of the Nurse Educator',
        'Maximizing the Scholar Experience',
        'Introduction to the Role of the Nurse Educator',
        'Grant Writing',
        'Disrupting College: How Disruptive Innovation Can Deliver Quality and Affordability to Postsecondary Education',
        'Unfolding Case Studies',
        'Writing for Publication',
        'Succeeding as a Nurse Educator: Making a Smooth  Transition to the Faculty Role - 1',
        'Charting Nursing&#039;s Future - Implementing the IOM Future of Nursing Report - Part I',
        'Annual Meeting: 2011 - Education Progression for NJ: Ensuring a Diverse and Qualified Nursing Workforce for Tomorrow',
        'Teaching and Learning in Online Courses',
        'Presenting Yourself Professionally ',
        'Charting Nursing&#039;s Future - Implementing the IOM Future of Nursing Report - Part II',
        'Professional Self-Presentation: Strategies for Success',
        'The Ideal Academic Appointment',
        'Finding the Ideal Academic Appointment',
        'Assessing and Evaluating Learning',
        'Succeeding as a Nurse Educator: Making a Smooth  Transition to the Faculty Role - 2',
        'Charting Nursing&#039;s Future - Implementing the IOM Future of Nursing Report - Part III',
        'Choosing and Using Advisors, Montors and Coaches',
        'The Nursing Shortage and New Jersey',
        'Building the Science of Nursing Education',
        'Nursing in New Jersey at a Glance: 2012',
        'Annual Meeting: 2012 - Leadership for a Lifetime: Shaping Gerontology Education and Policy in the Garden State',
        'Creating Innovation Models of Clinical Nursing Education Article',
        'Evaluating Innovations in Nursing Education Powerpoint',
        'ICE Pilot 1&quot;SHARES&quot; presentation- Georgian Court/Meridian Health School of Nursing',
        'ICE Pilot 2 &quot;Collaborative Project to Develop Preceptors&quot; Presentation- Fairleigh Dickinson University/Holyname Medical Center',
        'ICE Pilot 3 &quot; A Simulation Partnership&quot; Presentation- Rutgers University, Newark College of Nursing/ St. Peter&#039;s University Hospital',
        'ICE Pilot 4 &quot;Establishment of a D.E.U. in an Inner City Medical Center&quot; Presentation-William Paterson University/ St. Josephs Medical Center',
        'The New Jersey Imperative ',
        'Creating and Launching Innovative Nursing Education Programs: Perils and Pearls',
        'Dedicated Education Units: A Partnership Model that Works',
        'Clinical Faculty Coordinator Development and Adaptation of the Portland Model to Long-Term Care Settings',
        'Project PDQ: Partnering for Dedicated Education Unit Development and Quality ',
        'Dedicated Education Units: Practice Perspective',
        'Dedicated Education Unit: Implementation Checklist',
        'Doctoral Education in Nursing',
        'The Unacknowledged Language Conditions of Workplace Bullying',
        'Scale, Causes, and Implications of the Primary Care Nursing Shortage',
        'Annual Meeting 2014 - Disrupting Health Care Education',
        'Annual Meeting 2014: Breaking the Rules: Redesigning the Educational Endeavor for Nursing',
        'Annual Meeting 2014: Innovations in Nursing Education:  Aligning Education with the Needs of the Public',
        'Annual Meeting 2014: Trends Impacting the Future of Health Care and Nursing: Away from Acute, Episodic Care&hellip;.Where to?',
        'Annual Meeting 2014: Preparing Nurses for the Shift from Acute &amp; Episodic Care to Health ',
        'What Factors Affect Nurse Practitioners&rsquo; Provision of Primary Care? ',
        'The Role of Physician Assistants and Advance Practice Nurses in Primary Care: Predictors and Outcomes',
        'Innovation in Clinical Nursing Education: Retooling the Old Model for a 21st-Century Workforce',
        'Quality and Safety Education for Nurses (QSEN) Learning Modules',
        'The Nurse Faculty Shortage and New Jersey',
        'The Future of the Nursing Workforce: National- and State-Level Projections, 2012-2025',
        'Charting Nursing&#039;s Future - RWJF Archives',
        'Publications Reporting Findings from EIN-Funded Studies  ',
        'A bold new vision for America&rsquo;s health care system',
        'Interprofessional Collaboration and Education: Working together to ensure excellence in health care.',
        'Addressing the Looming Demand for Care as Americans Age: How Nurses are Reshaping Long-Term Services and Supports',
        'Lessons From the Field Promising Interprofessional Collaboration Practices',
      );
  }
}